//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTaxCalculator.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesTaxCalculator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TaxTabTitle {
            get {
                return ResourceManager.GetString("CalculateRateButton", resourceCulture);
            }
        }
        
        public static string RateTabTitle {
            get {
                return ResourceManager.GetString("CityPlaceholder", resourceCulture);
            }
        }
        
        public static string ZipPlaceholder {
            get {
                return ResourceManager.GetString("CountryCodeInvalidMessage", resourceCulture);
            }
        }
        
        public static string CountryPlaceholder {
            get {
                return ResourceManager.GetString("CountryPlaceholder", resourceCulture);
            }
        }
        
        public static string CityPlaceholder {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        public static string CalculateRateButton {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredMessage", resourceCulture);
            }
        }
        
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("NumberInvalidMessage", resourceCulture);
            }
        }
        
        public static string StateInvalidMessage {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        public static string OkButton {
            get {
                return ResourceManager.GetString("RateTabTitle", resourceCulture);
            }
        }
        
        public static string ValidationFailedMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        public static string ZipCodeInvalidMessage {
            get {
                return ResourceManager.GetString("StateInvalidMessage", resourceCulture);
            }
        }
        
        public static string CountryCodeInvalidMessage {
            get {
                return ResourceManager.GetString("TaxTabTitle", resourceCulture);
            }
        }
        
        public static string InternetConnectionRequiredMessage {
            get {
                return ResourceManager.GetString("ValidationFailedMessage", resourceCulture);
            }
        }
        
        public static string NumberInvalidMessage {
            get {
                return ResourceManager.GetString("ZipCodeInvalidMessage", resourceCulture);
            }
        }
        
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("ZipPlaceholder", resourceCulture);
            }
        }
    }
}
